theme: osuny-hugo-theme-aaa

## ADVANCED
paginate: 18
enableRobotsTXT: true

## MODULE
module:
  _merge: deep

## PARAMS
params:
  _merge: deep
  cookie_banner:
    enable: false
  posts:
    list:
      show_categories: true
      truncate_description: 150
  pages:
    list:
      truncate_description: 250

build:
  writeStats: true

removePathAccents: true
