theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  _merge: deep
  cookie_banner:
    enable: false
  posts:
    index:
      show_categories: true
      truncate_description: 150
      layout: grid
  pages:
    index:
      truncate_description: 250
build:
  writeStats: true
