en:
  title: Communication et démocratie
  contentDir: content/en
  languageCode: en
  languageName: English
fr:
  title: Communication et démocratie
  contentDir: content/fr
  languageCode: fr
  languageName: Français
